[mongodb]
mongodb.adamshafi.shop
[catalogue]
catalogue.adamshafi.shop
[user]
user.adamshafi.shop
[cart]
cart.adamshafi.shop
[front]
frontend.adamshafi.shop
[redis]
redis.adamshafi.shop
[shipping]
shipping.adamshafi.shop
[mysql]
mysql.adamshafi.shop
[rabbitmq]
rabbitmq.adamshafi.shop
[payment]
payment.adamshafi.shop